datasets:
  # unnatural_instruction:
  #   data_type: text
  #   build_info:
  #     ann_path: /path/to/unnatural-instructions/data/unnatural_instruction_filer.json

  unnatural_instruction:
    data_type: text
    build_info:
      ann_path: /ibex/project/c2133/minigpt4_v2_dataset/unnatural-instructions/data/unnatural_instruction_filer.json