datasets:
  flickr_ObjectToPhrase:
    data_type: images
    build_info:
      image_path: /ibex/project/c2133/minigpt4_v2_dataset/flickr/images
      ann_path: /ibex/project/c2090/minigptv2_dataset/filtered_flickr/phrasetobbox.json
