wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698040478.151963
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      3:
      - 1
      - 13
      - 23
      4: 3.9.16
      5: 0.14.2
      6: 4.31.0
      8:
      - 5
