datasets:
  invrefcoco:
    data_type: images
    build_info:
      image_path: /ibex/reference/CV/COCO/cocoapi/data/2014/images/jpeg/train
      ann_path: /ibex/project/c2133/object_detection_datasets/
      dataset: invrefcoco
      splitBy: unc