datasets:
  # refvg:
  #   data_type: images
  #   build_info:
  #     data_dir: /path/to/visual_genome

  refvg:
    data_type: images
    build_info:
      data_dir: /ibex/project/c2090/minigptv2_dataset/visual_genome