model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: ""
  ckpt: ""
  lora_r: 64
  lora_alpha: 16


datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  max_new_tokens: 20
  name: minigptv2_evaluation
  batch_size: 10
  eval_file_path: /path/to/eval/annotation/path  # annotation file
  img_path: /path/to/eval/image/path    # image file path
  save_path: /path/to/save/path   # saved result
  

  

