datasets:
  # multitask_conversation:
  #   data_type: images
  #   build_info:
    
  #     image_path: /path/to/coco/images
  #     ann_path: /path/to/multitask_conversation/multi_task_conversation.json

  multitask_conversation:
    data_type: images
    build_info:
    
      image_path: /ibex/reference/CV/COCO/cocoapi/data/2014/images/jpeg/train
      ann_path: /ibex/project/c2090/minigptv2_dataset/multitask_conversation/multi_task_conversation.json