 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  ok_vqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    # build_info:
    #   # Be careful not to append minus sign (-) before split to avoid itemizing
    #   annotations:
    #     train:
    #       url:
    #           # TODO make this order insensitive
    #           - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/okvqa_train.json
    #       storage:
    #           - /path/to/okvqa/annotations/okvqa_train.json
    #   images:
    #       storage: /path/to/okvqa/images


    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              # TODO make this order insensitive
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/okvqa_train.json
              # - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/OpenEnded_mscoco_train2014_questions.json
              # - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/okvqa/mscoco_train2014_annotations.json
          storage:
              - /ibex/project/c2133/minigpt4_v2_dataset/okvqa_v2/annotations/okvqa_train.json
      images:
          storage: /ibex/reference/CV/COCO/cocoapi/data/2014/images/jpeg