datasets:
  # llava_detail:
  #   data_type: images
  #   build_info:
  #     image_path: /path/to/coco/images
  #     ann_path: /path/to/llava/detail_23k.json

  llava_detail:
    data_type: images
    build_info:
      image_path: /ibex/reference/CV/COCO/cocoapi/data/2014/images/jpeg/train
      ann_path: /ibex/project/c2133/minigpt4_v2_dataset/llava/detail_23k.json