datasets:
  # textcaps_caption:
  #   data_type: images
    
  #   build_info:
  #     image_path: /path/to/TextCaps/train_images
  #     ann_path: /path/to/TextCaps/TextCaps_0.1_train.json

  textcaps_caption:
    data_type: images
    
    build_info:
      image_path: /ibex/project/c2133/minigpt4_v2_dataset/TextCaps/train_images
      ann_path: /ibex/project/c2133/minigpt4_v2_dataset/TextCaps/TextCaps_0.1_train.json


