# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  engagenet: # same as the name of the train_config yaml file
    # data_dir: ${env.data_dir}/datasets
    data_type: images # let it be images for now even if it is videos

    build_info: # this is the information needed to build the dataset
      # Be careful not to append minus sign (-) before split to avoid itemizing
      ann_paths: [
          /home/tony/nvme2tb/ieee_fer_dpo/engagenet_captions/train_val_filter_cap.json,
        ] # list of paths to annotation files
      vis_root: /home/tony/nvme2tb/EngageNetFrames/train_val
      model_name: "pretrain_vicuna0" # Language Model Name (available: llama2, mistral)
      storage: /home/tony/nvme2tb/ieee_fer_dpo/engagenet_captions
      prompts: /home/tony/nvme2tb/ieee_fer_dpo/prompts/instruction_align.txt
      questions: /home/tony/nvme2tb/ieee_fer_dpo/prompts/daisee_questions.txt
